In [14]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
import re
import numpy as np
import json
import matplotlib
# from pandas import json_normalize

In [15]:
api_key = "37f7363033e17d80a1b9c192e6981287"

In [16]:
namesimdb = [f"tt00000{number}" for number in range(10,100)]
namesimdb

['tt0000010',
 'tt0000011',
 'tt0000012',
 'tt0000013',
 'tt0000014',
 'tt0000015',
 'tt0000016',
 'tt0000017',
 'tt0000018',
 'tt0000019',
 'tt0000020',
 'tt0000021',
 'tt0000022',
 'tt0000023',
 'tt0000024',
 'tt0000025',
 'tt0000026',
 'tt0000027',
 'tt0000028',
 'tt0000029',
 'tt0000030',
 'tt0000031',
 'tt0000032',
 'tt0000033',
 'tt0000034',
 'tt0000035',
 'tt0000036',
 'tt0000037',
 'tt0000038',
 'tt0000039',
 'tt0000040',
 'tt0000041',
 'tt0000042',
 'tt0000043',
 'tt0000044',
 'tt0000045',
 'tt0000046',
 'tt0000047',
 'tt0000048',
 'tt0000049',
 'tt0000050',
 'tt0000051',
 'tt0000052',
 'tt0000053',
 'tt0000054',
 'tt0000055',
 'tt0000056',
 'tt0000057',
 'tt0000058',
 'tt0000059',
 'tt0000060',
 'tt0000061',
 'tt0000062',
 'tt0000063',
 'tt0000064',
 'tt0000065',
 'tt0000066',
 'tt0000067',
 'tt0000068',
 'tt0000069',
 'tt0000070',
 'tt0000071',
 'tt0000072',
 'tt0000073',
 'tt0000074',
 'tt0000075',
 'tt0000076',
 'tt0000077',
 'tt0000078',
 'tt0000079',
 'tt0000080',
 'tt0000081',
 'tt0000082',
 'tt0000083',
 'tt0000084',
 'tt0000085',
 'tt0000086',
 'tt0000087',
 'tt0000088',
 'tt0000089',
 'tt0000090',
 'tt0000091',
 'tt0000092',
 'tt0000093',
 'tt0000094',
 'tt0000095',
 'tt0000096',
 'tt0000097',
 'tt0000098',
 'tt0000099']

In [17]:
def imdb_people_id(namesimdb):
    url = f"https://api.themoviedb.org/3/find/{namesimdb}?api_key={api_key}&language=en-US&external_source=imdb_id"
    re = requests.get(url).json()['movie_results'][0]
    
    return {"name": re["original_title"]}

In [18]:
except_ids = []
df_tmdb = pd.DataFrame(columns = ["name"])

for namesimdb in namesimdb:
    try:
        df_tmdb = df_tmdb.append(imdb_people_id(namesimdb),ignore_index=True)
    except:
        except_ids.append(namesimdb)
        
df_tmdb

                                                 name
0                 La Sortie de l'Usine Lumière à Lyon
1                             Akrobatisches Potpourri
2                    L'arrivée d'un train à La Ciotat
3   Neuville-sur-Saône: Débarquement du congrès de...
4                                  Arroseur et arrosé
5                                 Autour d'une Cabine
6                              Barque Sortant du Port
7                            Italienischer Bauerntanz
8                                Das boxende Känguruh
9                                    The Clown Barber
10                                     The Derby 1895
11                                      Les forgerons
12                                    Baignade en mer
13                          Opening of the Kiel Canal
14                                    Partie d'écarté
15                        Place des Cordeliers à Lyon
16                       La pêche aux poissons rouges
17                                      Repas de bébé
18                                 Rough Sea at Dover
19                            Le saut à la couverture
20                              Die Serpentintänzerin
21                                         La Voltige
22             Arrivée d'un train (gare de Vincennes)
23                  L'Arroseur (Watering the Flowers)
24                                   Awakening of Rip
25                                      The Ball Game
26                                  Bataille de neige
27                                The Boxing Kangaroo
28                    Boxing Match; or, Glove Contest
29                                   Carga de rurales
30                                    Dancing Darkies
31                                 Défense d'afficher
32                                Démolition d'un mur
33           Escamotage d'une dame chez Robert-Houdin
34                          Exit of Rip and the Dwarf
35                         Feira de Gado na Corujeira
36               Départ de Jérusalem en chemin de fer
37                                Le manoir du diable